language: cpp

jobs:
  include:
    - name: Ubuntu 14.04 build
      os: linux
      dist: trusty

    - name: macOS build
      os: osx
    
    - name: Windows (VS2017 x64) build
      os: windows

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config Release