language: cpp

jobs:
  include:
    - name: Ubuntu 14.04 build
      os: linux
      dist: trusty
      env:
        - BINARY_SUFFIX: _linux

    - name: macOS build
      os: osx
      env:
        - BINARY_SUFFIX: _macos
    
    - name: Windows (VS2017 x64) build
      os: windows
      env:
        - BINARY_SUFFIX: .exe

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config Release
  - cd ..

after_success:
  - mv build/danmaku2ass danmaku2ass${BINARY_SUFFIX}
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh danmaku2ass${BINARY_SUFFIX}

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/